package com.example.userapi.enums;

public enum AuditEventType {
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    PASSWORD_CHANGE,
    ROLE_CHANGE,
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_DISABLED,
    ACCOUNT_ENABLED,
    WALLET_TOP_UP,
    WALLET_PAYMENT,
    STOCK_WATCHLIST_ADD,
    STOCK_WATCHLIST_REMOVE
}
